apiVersion: v1
kind: PersistentVolume
metadata:
  name: numbers-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/numbers-volume
