apiVersion: v1
kind: Pod
metadata:
  name: volume-inspector
spec:
  containers:
  - name: inspector
    image: busybox
    command: ['sleep', '3600']
    volumeMounts:
    - mountPath: '/mnt'
      name: 'numbers-volume'
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: "numbers-volume"
    emptyDir: {}

